export type BranesxMarketplaceFormula = {
  id: string;
  name: string;
  category: string;
  status: "proven" | "emerging" | "experimental";
  purpose: string;
  environments: string[];
  formula: string[];
  protectedSteps: number;
  associatedScripts: number;
  associatedScreeners: number;
};

export const BRANESX_MARKETPLACE_FORMULAS: BranesxMarketplaceFormula[] = [
  {
    id: "value-anchor",
    name: "Value Anchor",
    category: "Sales",
    status: "proven",
    purpose: "Establish measurable value before price, implementation, or perceived risk controls the conversation.",
    environments: ["Sales meetings", "Renewals", "Inbound calls"],
    formula: ["Clarify the goal", "Identify decision criteria", "Quantify meaningful value", "Address perceived risk", "Secure the next commitment"],
    protectedSteps: 1,
    associatedScripts: 27,
    associatedScreeners: 6,
  },
  {
    id: "cold-entry",
    name: "Cold Entry",
    category: "Outbound Calls",
    status: "proven",
    purpose: "Earn enough attention to establish relevance before the recipient disengages.",
    environments: ["Cold calls", "Telemarketing", "Appointment setting"],
    formula: ["Establish relevance immediately", "Lower resistance", "Create a reason to continue", "Qualify fit", "Request the next action"],
    protectedSteps: 2,
    associatedScripts: 34,
    associatedScreeners: 12,
  },
  {
    id: "gatekeeper-navigation",
    name: "Gatekeeper Navigation",
    category: "Outbound Calls",
    status: "emerging",
    purpose: "Navigate screeners professionally without misrepresentation or unnecessary friction.",
    environments: ["Reception", "Executive assistants", "Call screening"],
    formula: ["Respect the screener's role", "State legitimate relevance", "Reduce perceived interruption", "Request the appropriate path"],
    protectedSteps: 2,
    associatedScripts: 16,
    associatedScreeners: 14,
  },
  {
    id: "inbound-resolution",
    name: "Inbound Resolution",
    category: "Incoming Calls",
    status: "proven",
    purpose: "Move an incoming caller from frustration or uncertainty toward a clear, owned resolution.",
    environments: ["Customer service", "Help desk", "Call centers"],
    formula: ["Acknowledge the caller's reality", "Identify the actual request", "Separate policy from possibility", "Offer the best available resolution", "Confirm ownership and next step"],
    protectedSteps: 1,
    associatedScripts: 29,
    associatedScreeners: 8,
  },
  {
    id: "retention-recovery",
    name: "Retention Recovery",
    category: "Incoming Calls",
    status: "proven",
    purpose: "Understand the true reason for departure and preserve the relationship without sounding desperate.",
    environments: ["Cancellation calls", "Renewals", "Account recovery"],
    formula: ["Let the reason surface", "Distinguish symptom from cause", "Validate without surrendering value", "Offer the right recovery path", "Confirm the customer's decision"],
    protectedSteps: 2,
    associatedScripts: 21,
    associatedScreeners: 7,
  },
  {
    id: "negotiation-leverage",
    name: "Negotiation Leverage",
    category: "Negotiation",
    status: "proven",
    purpose: "Protect leverage while discovering what the other side values enough to trade.",
    environments: ["In person", "Phone", "Video meetings"],
    formula: ["Define the objective and walk-away", "Discover priorities", "Separate positions from interests", "Trade rather than concede", "Close with explicit terms"],
    protectedSteps: 2,
    associatedScripts: 31,
    associatedScreeners: 9,
  },
  {
    id: "trust-repair",
    name: "Trust Repair",
    category: "Difficult Conversations",
    status: "emerging",
    purpose: "Rebuild enough trust for useful communication after disappointment, error, or conflict.",
    environments: ["Customer meetings", "Leadership", "Personal conversations"],
    formula: ["Acknowledge impact", "Clarify responsibility", "Separate explanation from excuse", "Offer credible repair", "Create a testable next step"],
    protectedSteps: 1,
    associatedScripts: 19,
    associatedScreeners: 4,
  },
  {
    id: "executive-brief",
    name: "Executive Brief",
    category: "Presentations",
    status: "proven",
    purpose: "Present the decision, evidence, risk, and requested action without burying the point.",
    environments: ["Board meetings", "Status updates", "Executive reviews"],
    formula: ["Lead with the decision", "State what changed", "Show the evidence", "Name the risk", "Request the action"],
    protectedSteps: 1,
    associatedScripts: 24,
    associatedScreeners: 5,
  },
  {
    id: "story-to-action",
    name: "Story to Action",
    category: "Influence",
    status: "emerging",
    purpose: "Turn attention into meaning and meaning into a clear audience action.",
    environments: ["Social video", "Live events", "Brand presentations"],
    formula: ["Open with human tension", "Make the audience recognize themselves", "Deliver the shift", "Connect the shift to value", "Give one clear action"],
    protectedSteps: 2,
    associatedScripts: 22,
    associatedScreeners: 5,
  },
  {
    id: "legal-position",
    name: "Legal Position",
    category: "Legal",
    status: "experimental",
    purpose: "Organize facts, authority, exposure, and desired resolution before legal communication.",
    environments: ["Client calls", "Settlement discussions", "Internal review"],
    formula: ["Separate facts from claims", "Identify controlling authority", "Map exposure", "Define the requested resolution"],
    protectedSteps: 3,
    associatedScripts: 11,
    associatedScreeners: 7,
  },
  {
    id: "decision-clarity",
    name: "Decision Clarity",
    category: "Leadership",
    status: "proven",
    purpose: "Move a group from competing information toward an explicit and owned decision.",
    environments: ["Team meetings", "One-on-ones", "Decision reviews"],
    formula: ["Name the decision", "Define the criteria", "Surface consequential disagreement", "Choose and assign ownership", "Set the review condition"],
    protectedSteps: 1,
    associatedScripts: 26,
    associatedScreeners: 6,
  },
  {
    id: "objection-path",
    name: "Objection Path",
    category: "Sales",
    status: "proven",
    purpose: "Identify whether an objection is factual, emotional, procedural, or a disguised refusal before responding.",
    environments: ["Sales calls", "Demos", "Follow-ups"],
    formula: ["Let the objection finish", "Classify the objection", "Confirm the real concern", "Resolve only what is material", "Return to the decision"],
    protectedSteps: 2,
    associatedScripts: 38,
    associatedScreeners: 10,
  },
];
